<?php


class Credentials
{
    CONST TEXT_ALGORITHIMIA_API_KEY = '';
    CONST TEXT_NLU_WATSON_API_KEY = '';
    CONST IMAGE_GOOGLE_API_KEY = '';
    CONST IMAGE_GOOGLE_SEARCH_ENGINE_ID = '';
    CONST AUDIO_TXT_TO_SPEECH_API_KEY = '';
}